export const moduleName = "client-onboarding";
export {
  authenticateBusinessApiKey,
  authenticateBusinessUser,
  authenticateBusinessUserOrApiKey,
  handleBusinessAuthMe,
  handleBusinessAuthRefresh,
  handleBusinessAuthResetPassword,
  handleBusinessAuthSignOut,
  handleBusinessAuthSetPassword,
  handleBusinessAuthSignIn,
  handleCreateMyAdaAccount,
  handleCreateMyBusinessLinkedInstrument,
  handleCreateMyLinkedInstrument,
  handleCreateMyApiKey,
  handleAssignMyLinkedInstrumentToAda,
  handleGetMyAdaAccount,
  handleGetMyAdaBalance,
  handleGetMyAdaStatement,
  handleListMyBusinessLinkedInstruments,
  handleListMyLinkedInstruments,
  handleListMyAdaAccounts,
  handleListMyApiKeys,
  handleGetOrCreateMyOnboarding,
  handleRevokeMyApiKey,
  handleRotateMyApiKey,
  handleUpdateMyAdaAccount,
  handleUpdateMyBusinessLinkedInstrument,
  handleUpdateMyLinkedInstrument,
  handleRespondToMyOnboardingRfi,
  handleSaveMyOnboardingStep,
  handleSelfRegistrationInvitation,
  handleSubmitMyOnboarding,
  resetBusinessAuthSessionsForTest,
  setSupabaseBusinessAuthClientForTest,
  isValidEmail,
  normalizeEmail
} from "./self-registration.js";
export type { AuthenticatedBusinessApiKey, AuthenticatedBusinessUser, BusinessJwtSession } from "./self-registration.js";
